# Introduction to TensorFlow

> Constants, variables, and placeholders

郭耀仁

## 大綱

- 常數
- 變數
- Placeholders

## 常數 Constants

## 如何宣告張量為常數

- `tf.constant()`
- `tf.zeros()`
- `tf.ones()`
- `tf.fill()`
- `tf.range()`
- `tf.random_normal()`
- `tf.random_uniform()`

## 如何跟 NumPy 對應

|NumPy|TensorFlow|
|:----|:---------|
|`np.array()`|`tf.constant()`|
|`np.zeros()`|`tf.zeros()`|
|`np.ones()`|`tf.ones()`|
|`np.full()`|`tf.fill()`|
|`np.arange()`|`tf.range()`|
|`np.random.normal()`|`tf.random_normal()`|
|`np.random.uniform()`|`tf.random_uniform()`|

In [1]:
# np.array() vs. tf.constant()
import numpy as np
import tensorflow as tf

const_tensor = tf.constant(24)
print(np.array(24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

24
24


In [2]:
# np.zeros() vs. tf.zeros() 
import numpy as np
import tensorflow as tf

const_tensor = tf.zeros(24)
print(np.zeros(24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# np.ones() vs. tf.ones()
import numpy as np
import tensorflow as tf

const_tensor = tf.ones(24)
print(np.ones(24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
# np.full() vs. tf.fill()
import numpy as np
import tensorflow as tf

const_tensor = tf.fill((24,), 24)
print(np.full(24, (24,)))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24]
[24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24]


In [5]:
# np.arange() vs. tf.range()
import numpy as np
import tensorflow as tf

const_tensor = tf.range(24)
print(np.arange(24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
# np.random.normal() vs. tf.random_normal()
import numpy as np
import tensorflow as tf

const_tensor = tf.random_normal((24,))
print(np.random.normal(size=24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[ 1.7803798  -3.04903426 -0.2987851   0.22826641  0.18628042 -1.53056876
 -0.65848798  0.48863073 -0.13545455  1.21544199 -1.06333225  1.07780844
  0.25110527  0.34818325 -1.17565631  1.0913382   0.539075   -0.22090564
  0.49246171 -0.29594903  1.49562126 -0.00767516 -0.68665798 -0.25182797]
[ 0.17294754  0.14567992  0.76818174  1.211184   -0.45513585  0.9712116
 -2.591927   -0.49827662  1.1639647   0.28426954 -0.36490804 -0.79622376
  2.187979   -0.26343167 -1.247932   -0.08046219 -1.1427915  -0.7130565
 -1.9631377   1.2381777  -1.585786    0.5103205  -0.71222436  0.13813359]


In [7]:
# np.random.uniform() vs. tf.random_uniform()
import numpy as np
import tensorflow as tf

const_tensor = tf.random_uniform((24,))
print(np.random.uniform(size=24))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[0.56970599 0.83830163 0.89949476 0.11449799 0.1265873  0.83112702
 0.02602302 0.21712078 0.32233186 0.03048527 0.89481081 0.46758448
 0.50782919 0.58300636 0.88517703 0.4434022  0.84023983 0.78317041
 0.71383656 0.55727618 0.61610275 0.92073169 0.04686731 0.26979706]
[0.00805461 0.8658891  0.5277964  0.6317295  0.9720731  0.40967023
 0.63836503 0.45727897 0.81815207 0.2918688  0.05865467 0.03776884
 0.79753244 0.02630234 0.21009135 0.9349235  0.7058486  0.21801853
 0.09616399 0.644727   0.14500451 0.94423234 0.9437436  0.99027586]


## 如何使用 TensorFlow 處理矩陣

- `tf.reshape()`
- `tf.eye()`
- `tf.diag()`
- `tf.matrix_transpose()`
- `tf.matmul()`

## 如何跟 NumPy 對應

|NumPy|TensorFlow|
|:----|:---------|
|`arr.reshape()`|`tf.reshape()`|
|`np.eye()`|`tf.eye()`|
|`np.diag()`|`tf.diag()`|
|`np.transpose()`|`tf.matrix_transpose()`|
|`np.dot()`|`tf.matmul()`|

In [8]:
# arr.reshape() vs. tf.reshape()
import numpy as np
import tensorflow as tf

const_tensor = tf.reshape(tf.range(24), (6, 4))
print(np.arange(24).reshape(6, 4))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [9]:
# np.eye() vs. tf.eye()
import numpy as np
import tensorflow as tf

const_tensor = tf.eye(3)
print(np.eye(3))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# np.diag() vs. tf.diag()
import numpy as np
import tensorflow as tf

const_tensor = tf.diag([1, 2, 3])
print(np.diag([1, 2, 3]))
with tf.Session() as sess:
    print(sess.run(const_tensor))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
# np.transpose() vs. tf.matrix_transpose()
import numpy as np
import tensorflow as tf

const_tensor = tf.ones((2, 4))
const_tensor_t = tf.matrix_transpose(const_tensor)
print(np.ones((2, 4)))
print(np.ones((2, 4)).T)
print("\n")
with tf.Session() as sess:
    print(sess.run(const_tensor))
    print(sess.run(const_tensor_t))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# np.dot() vs. tf.matmul()
import numpy as np
import tensorflow as tf

const_tensor = tf.ones((2, 2))
matrix_multiply = tf.matmul(const_tensor, const_tensor)
print(np.dot(np.ones((2, 2)), np.ones((2, 2))))
with tf.Session() as sess:
    print(sess.run(matrix_multiply))

[[2. 2.]
 [2. 2.]]
[[2. 2.]
 [2. 2.]]


## 隨堂練習

使用 TensorFlow 常數張量計算 $u^Tv$

$$u = \begin{bmatrix}
    4 \\
    -4 \\
    -3
\end{bmatrix}$$

$$v = \begin{bmatrix}
    4 \\
    2 \\
    4
\end{bmatrix}$$

## 隨堂練習

使用 TensorFlow 常數張量計算 $error$，其中 $error = y - y_{pred}$，而 $y_{pred} = X\theta$

$$
X = \begin{bmatrix}
    1 & 2 \\
    2 & 1 \\
    5 & 8 \\
    6 & 10 \\
\end{bmatrix}
$$


$$
\theta = \begin{bmatrix}
    1\\
    2\\
\end{bmatrix}
$$

$$
y = \begin{bmatrix}
    6\\
    4\\
    20\\
    23\\
\end{bmatrix}
$$

## 隨堂練習

使用 TensorFlow 常數張量計算 $W$ 中的所有數值總和、各欄總和與各列總和

$$
W = \begin{bmatrix}
    11 & 7 & 4 & 3 & 25 \\
    50 & 2 & 60 & 0 & 10 \\
\end{bmatrix}
$$

## 熟悉 NumPy 的 Python 使用者來說學習 TensorFlow 有很大優勢

<https://www.numpy.org/devdocs/user/quickstart.html>

## 變數 Variables

## 以 `tf.Variable()` 宣告

變數張量的值可以更動，模型訓練過程要持續更新的參數會以變數張量宣告

In [13]:
import tensorflow as tf

lucky_number = tf.Variable(24)
print(lucky_number)

Instructions for updating:
Colocations handled automatically by placer.
<tf.Variable 'Variable:0' shape=() dtype=int32_ref>


## 宣告變數張量不如常數張量那麼單純

- 宣告變數張量的初始值、類型與外觀
- 初始化變數張量

## 如果宣告的變數張量沒有經過初始化，將會得到錯誤

In [14]:
import tensorflow as tf

lucky_number = tf.Variable(24)
with tf.Session() as sess:
    print(sess.run(lucky_number))

FailedPreconditionError: Attempting to use uninitialized value Variable_1
	 [[{{node _retval_Variable_1_0_0}}]]

## 該如何修正呢？

將變數張量的 `initializer` 屬性放入 Session 中執行

In [15]:
import tensorflow as tf

lucky_number = tf.Variable(24)
with tf.Session() as sess:
    sess.run(lucky_number.initializer)
    print(sess.run(lucky_number))

24


## 透過 `.assign()` 賦值

In [16]:
import tensorflow as tf

lucky_number = tf.Variable(24)
assign_op = lucky_number.assign(7)
with tf.Session() as sess:
    sess.run(lucky_number.initializer)
    # sess.run(assign_op)
    print(sess.run(lucky_number))

24


## 重新賦值也是一種運算（operation），必須放入 Session 執行

In [17]:
import tensorflow as tf

lucky_number = tf.Variable(24)
assign_op = lucky_number.assign(7)
with tf.Session() as sess:
    sess.run(lucky_number.initializer)
    sess.run(assign_op)
    print(sess.run(lucky_number))

7


## 變數張量被宣告之後，重新賦值時必須要注意類型

In [18]:
import tensorflow as tf

lucky_number = tf.Variable(24)
assign_op = lucky_number.assign(7.0)
with tf.Session() as sess:
    sess.run(lucky_number.initializer)
    sess.run(assign_op)
    print(sess.run(lucky_number))

TypeError: Expected int32 passed to parameter 'value' of op 'Assign', got 7.0 of type 'float' instead.

## 變數張量被宣告之後，重新賦值時必須要注意外觀

In [19]:
import tensorflow as tf

lucky_numbers = tf.Variable([7, 24])
assign_op = lucky_numbers.assign(87)
with tf.Session() as sess:
    sess.run(lucky_numbers.initializer)
    sess.run(assign_op)
    print(sess.run(lucky_numbers))

ValueError: Shapes must be equal rank, but are 1 and 0 for 'Assign_3' (op: 'Assign') with input shapes: [2], [].

## TensorFlow 外觀的註記與 ndarray 相同

- 零維：`()`
- 一維：`(m,)`
- 二維：`(m, n)`
- 三維：`(q, m, n)`

In [20]:
import numpy as np

zero_d = np.array(24)
one_d = np.arange(24)
two_d = np.arange(24).reshape(6, 4)
three_d = np.arange(24).reshape(2, 3, 4)
print(zero_d.shape)
print(one_d.shape)
print(two_d.shape)
print(three_d.shape)

()
(24,)
(6, 4)
(2, 3, 4)


## 可以使用 `.get_shape()` 確認 Tensor 外觀

In [21]:
import tensorflow as tf

zero_d = tf.Variable(24)
one_d = tf.reshape(tf.Variable(tf.range(24)), (24,))
two_d = tf.reshape(tf.Variable(tf.range(24)), (6, 4))
three_d = tf.reshape(tf.Variable(tf.range(24)), (2, 3, 4))
print(zero_d.get_shape())
print(one_d.get_shape())
print(two_d.get_shape())
print(three_d.get_shape())

()
(24,)
(6, 4)
(2, 3, 4)


## `tf.GradientTape()` 計算特定資料點的斜率

In [2]:
# 如果想要跑以下三個儲存格，必須重新啟動 Kernel
import tensorflow as tf

tf.enable_eager_execution()
x = tf.Variable(1.0) # eager execution 不需要初始化變數張量
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x) # y = x**2
grad = tape.gradient(y, x) # y = 2*x
print(grad.numpy())

2.0


In [3]:
x = tf.Variable(0.0) # eager execution 不需要初始化變數張量
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x) # y = x**2
grad = tape.gradient(y, x) # y = 2*x
print(grad.numpy())

0.0


In [3]:
x = tf.Variable(-1.0) # eager execution 不需要初始化變數張量
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x) # y = x**2
grad = tape.gradient(y, x) # y = 2*x
print(grad.numpy())

0.0


## 隨堂練習

以 `tf.GradientTape()` 與 eager execution 計算 $y = 2x - 1$ 在 x 為 1, 0, -1 的梯度

In [8]:
x = tf.Variable(-1.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 2*x-1
grad = tape.gradient(y, x)
print(grad.numpy())

2.0


In [9]:
x = tf.Variable(0.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 2*x-1
grad = tape.gradient(y, x)
print(grad.numpy())

2.0


In [10]:
x = tf.Variable(1.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 2*x-1
grad = tape.gradient(y, x)
print(grad.numpy())

2.0


## Placeholders

## 以 `tf.placeholder()` 宣告

## Placeholder 作為 TensorFlow 模型的資料輸入口

- Feed dict 資料要以 Python dict 的格式餵入
- Fetch 是模型運算的輸出，類型是 `ndarray`

## 可以把 Placeholder 想成像是 `None` 或 `np.NaN`

In [22]:
import numpy as np

none_list = [None for _ in range(3)]
nan_arr = [np.NaN for _ in range(3)]
print("Pythonic:")
print(len(none_list))
print(none_list)
print("NumPy:")
print(len(nan_arr))
print(nan_arr)

Pythonic:
3
[None, None, None]
NumPy:
3
[nan, nan, nan]


In [23]:
import numpy as np

none_list = [None for _ in range(3)]
nan_arr = [np.NaN for _ in range(3)]
lucky_numbers = [7, 24, 34]
for i in range(3):
    none_list[i] = lucky_numbers[i]
    nan_arr[i] = lucky_numbers[i]
print(none_list)
print(nan_arr)

[7, 24, 34]
[7, 24, 34]


In [24]:
import tensorflow as tf

tf_placeholder = tf.placeholder(tf.int32, shape=(3,))
print(tf_placeholder)
print(tf_placeholder.get_shape()[0])

Tensor("Placeholder:0", shape=(3,), dtype=int32)
3


## 將資料以 dict 餵入 placeholder

語法為：

```python
import tensorflow as tf

my_ph = tf.placeholder(...)
my_op = ...
feed_dict = {
  my_ph: ...
}
with tf.Session() as sess:
  fetch = sess.run(my_op, feed_dict)
```

In [25]:
import tensorflow as tf

tf_placeholder = tf.placeholder(tf.int32, shape=(3,))
with tf.Session() as sess:
    fetch = sess.run(tf_placeholder, {tf_placeholder: [7, 24, 34]})

print(fetch)
print(type(fetch))

[ 7 24 34]
<class 'numpy.ndarray'>


## Placeholders 也很嚴謹

不同的外觀不能餵入

In [26]:
import tensorflow as tf

tf_placeholder = tf.placeholder(dtype=tf.int32, shape=(3,))
with tf.Session() as sess:
    print(sess.run(tf_placeholder, {tf_placeholder: [7, 24]}))

ValueError: Cannot feed value of shape (2,) for Tensor 'Placeholder_2:0', which has shape '(3,)'

## Placeholders 也很嚴謹

外觀相同、不同的資料類型則會做隱性轉換

In [27]:
import tensorflow as tf

tf_placeholder = tf.placeholder(dtype=tf.int32, shape=(3,))
with tf.Session() as sess:
    print(sess.run(tf_placeholder, {tf_placeholder: [7.0, 24.0, 34.0]}))

[ 7 24 34]


## 隨堂練習

以 TensorFlow 的 placeholder 張量將五組華氏溫度轉換為攝氏溫度。

$$C = \frac{(F - 32) \times 5}{9}$$

In [28]:
city_temps_f = [59, 30, 45, 28, 47] # Taipei, New York, London, Reykjavik, Tokyo

In [29]:
import tensorflow as tf

city_temps_f_ph = tf.placeholder(dtype=tf.float32, shape=(5,))
f_to_c_op = (city_temps_f_ph - 32)*5/9
feed_dict = {
  city_temps_f_ph: city_temps_f
}
with tf.Session() as sess:
    city_temps_c_arr = sess.run(f_to_c_op, feed_dict)
print(city_temps_c_arr)

[15.000001  -1.1111112  7.2222223 -2.2222223  8.333334 ]


## 隨堂練習

以 TensorFlow 的 placeholder 張量計算五個球員的 BMI

$$BMI = \frac{weight_{kg}}{height_{m}^2}$$

In [30]:
# Shaq, Dirk, LeBron, MJ, Nash
player_heights = [216, 213, 203, 198, 191]
player_weights = [147, 111, 113, 98, 82]

In [31]:
import tensorflow as tf

player_heights_ph = tf.placeholder(dtype=tf.float32, shape=(5,))
player_weights_ph = tf.placeholder(dtype=tf.float32, shape=(5,))
bmi_op = player_weights_ph / (player_heights_ph*0.01)**2
feed_dict = {
  player_heights_ph: player_heights,
  player_weights_ph: player_weights
}
with tf.Session() as sess:
    bmi_arr = sess.run(bmi_op, feed_dict)
print(bmi_arr)

[31.507206 24.466047 27.421196 24.997452 22.477455]
